# Default values for argo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: stage
image_tag: 3.0-alpha-20210303-173025
app_name: spring-rest-demo
googlechat_secret: mikes-chat-secret
pipeline:
  enabled: "True"
  namespace: att-pipelines
